### ISSUE TITLE
Task::The admin can only add open seats belonging to the same account/accounts as admin

### ISSUE THREAD

**Issue by Adharshd** [rkulkar5/OnlineTAT#153] opened 2020-09-16 13:37 UTC

**Comment by Teja-swi** [comment] 2020-09-24 09:46
![image](https://user-images.githubusercontent.com/66815529/94128568-f0a30400-fe77-11ea-858e-7aef8e02c868.png)
![image](https://user-images.githubusercontent.com/66815529/94129279-cb62c580-fe78-11ea-991e-dc1363b082ef.png)
Tejaswi : Not Sure why a single ID is created 21 times

**Comment by Teja-swi** [comment] 2020-09-24 09:56
![image](https://user-images.githubusercontent.com/66815529/94130447-4aa4c900-fe7a-11ea-8bca-7a4c630b85a4.png)
Getting duplicate Ids

**Comment by Adharshd** [comment] 2020-09-30 11:55
Can you please retest the same?

**Comment by Teja-swi** [comment] 2020-09-30 16:01
ID is having space.

![image](https://user-images.githubusercontent.com/66815529/94710239-3d00af00-0364-11eb-861c-311e68100a4d.png)

**Comment by Adharshd** [comment] 2020-09-30 16:04
@samirghoshibm : Can you remove any space while creating the IDs?

**Comment by samirghoshibm** [comment] 2020-10-01 20:04
Fix is implemented. In the next build it will be available for test.

**Comment by Tatireddysreevani** [comment] 2020-10-05 12:16
![image](https://user-images.githubusercontent.com/61975055/95076093-f24db100-072e-11eb-9da5-45e8f51f9dd6.png)
I think here the problem is with IIB debeloper jobrole

**Comment by Tatireddysreevani** [comment] 2020-10-05 13:42
closing the issue as working fine

**Comment by Teja-swi** [comment] 2020-10-07 07:10
I think issue still exists.

![image](https://user-images.githubusercontent.com/66815529/95298803-46c16f80-089a-11eb-83bc-6145e78f9341.png)

**Comment by samirghoshibm** [comment] 2020-10-08 09:14
The fix for this has been implemented and checked into the repo late evening yesterday. Once the latest build is deployed, the fix can be verified.

**Closed as completed** 2020-10-08 13:11 UTC
Labels: Sprint-10
