### ISSUE TITLE
Percentage Calculation 

### ISSUE THREAD

**Issue by Teja-swi** [rkulkar5/OnlineTAT#293] opened 2020-11-06 07:49 UTC
Some discrepancy in percentage calculation

![image](https://user-images.githubusercontent.com/66815529/98339942-8ebaea00-2032-11eb-8f81-9b0e244b952d.png)

**Comment by rkulkar5** [comment] 2020-11-09 05:55
I could not reproduce the issue, I tried all the options both in cloud and local environment

**Comment by Teja-swi** [comment] 2020-11-09 08:50
@rkulkar5  Hi Rajesh, faced same issue today as well.

![image](https://user-images.githubusercontent.com/66815529/98519366-af837980-2296-11eb-8c8f-070b7b88a515.png)

**Comment by Teja-swi** [comment] 2020-11-09 09:17
Rajesh, I observed this is mainly happening with contractors as below.

Here, akil is initially a contractor updated to regular later.


![image](https://user-images.githubusercontent.com/66815529/98522216-6d5c3700-229a-11eb-9c18-96f3ae49fc15.png)

**Comment by Teja-swi** [comment] 2020-11-12 15:32
Hi Rajesh,

Faced same issue today as well

![image](https://user-images.githubusercontent.com/66815529/98960300-43b93f00-252a-11eb-8f03-9d080ae7df98.png)

![image](https://user-images.githubusercontent.com/66815529/98960347-592e6900-252a-11eb-9c53-52694babdea9.png)



Percentage  issue is affecting the records in Management - Exception approval page. Here you can see two records.

![image](https://user-images.githubusercontent.com/66815529/98966148-ef658d80-2530-11eb-9091-c91cd09fa25f.png)

**Comment by Teja-swi** [comment] 2020-11-23 08:44
on 23/11...faced the same issue again

![image](https://user-images.githubusercontent.com/66815529/99942611-f6dd3000-2d95-11eb-86dd-8a495551f724.png)

![image](https://user-images.githubusercontent.com/66815529/99942716-20965700-2d96-11eb-93a5-f27bb33125fc.png)

**Comment by Tatireddysreevani** [comment] 2020-11-26 06:10
Today i created two candidates, one regular and another contractor
added test configuration as 10 questions , 10 mins and 60%
while attempting quiz i answered 8 questions correctly out of 10, but got percentage of 60%.
![image](https://user-images.githubusercontent.com/61975055/100313917-8de6f980-2fdb-11eb-8714-1ee9b0a2c3bc.png)
![image](https://user-images.githubusercontent.com/61975055/100313987-ace58b80-2fdb-11eb-93af-9e6341ec17d4.png)
![image](https://user-images.githubusercontent.com/61975055/100314054-d1416800-2fdb-11eb-8c20-b47c8fdda289.png)
![image](https://user-images.githubusercontent.com/61975055/100314080-e0281a80-2fdb-11eb-9098-f4024610b6fb.png)
![image](https://user-images.githubusercontent.com/61975055/100314105-ecac7300-2fdb-11eb-81a7-3d185e692503.png)
for contractor employee i answered 8 questions correctly out of 10, but got percentage of 70%.

**Comment by rkulkar5** [comment] 2020-12-07 17:30
The issue was constantly reproduced in local when the quiz is configured for larger number of questions (say 40 / 50)
The root cause has been found and fixed the issue

Please re-test and verify the fix
thanks

**Comment by Tatireddysreevani** [comment] 2020-12-10 07:08
fixed

**Comment by Tatireddysreevani** [comment] 2020-12-10 09:53
![image](https://user-images.githubusercontent.com/61975055/101755871-6758b080-3afb-11eb-8b2b-c5adcc25d4c0.png)
again facing percentage issue, i got 180%

**Comment by rkulkar5** [comment] 2020-12-24 04:55
The previous issue of percentage doubling could have been due to data issue
Could you please watch the issue, and close if its not reproducible

**Comment by Tatireddysreevani** [comment] 2020-12-24 06:02
closing as we didn't faced this issue again

**Closed as completed by Tatireddysreevani** 2020-12-24 06:02 UTC
Labels: Issues after Sprint-9
